services:
  local_dev_atlas:
    image: mongodb/mongodb-atlas-local:8.0
    hostname: local_dev_atlas
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=fighteragents
      - MONGODB_INITDB_ROOT_PASSWORD=fighteragents
    volumes:
      - data:/data/db
      - config:/data/configdb
    networks:
      - fighteragents-network
  api:
    container_name: fighteragents-api
    build:
      context: ./fighteragents-api
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://fighteragents:fighteragents@local_dev_atlas:27017/?directConnection=true
    ports:
      - "8000:8000"
    env_file:
      - ./fighteragents-api/.env
    networks:
      - fighteragents-network
  ui:
    container_name: fighteragents-ui
    build:
      context: ./fighteragents-ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./fighteragents-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - fighteragents-network

volumes:
  data:
  config:

networks:
  fighteragents-network:
    name: fighteragents-network